import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import dynamic from 'next/dynamic';

// Components
import Footer from "@/components/shared/footer";
import { Providers } from "./providers";
import { WixClientContextProvider } from "@/context/wixContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
 
const DynamicComponentWithNoSSR = dynamic(
  () => import('@/components/shared/header'),
  { ssr: false }
)


export const metadata: Metadata = {
  title: "Minus Gaming",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable}`}

      >
        <WixClientContextProvider>
          <Providers>
              <DynamicComponentWithNoSSR />
            <main>{children}</main>
            <footer>
              <Footer />
            </footer>
          </Providers>
        </WixClientContextProvider>
      </body>
    </html>
  );
}